[package]
name = "aiyu-sorts"
version = "0.1.0"
authors = ["Aiyu Kamate <aiyukamat523@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
structopt = "0.3.21"
